import { PlayerInfo } from "../types/PlayerTypes";

export const dummyPlayerInfo: PlayerInfo[] = [
  {
    id: 1,
    name: "Serkan",
    age: 28,
    rating: 7.7,
    position: "Forvet",
    foot: "right",
    photo: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    name: "Metehan",
    age: 24,
    rating: 6.6,
    position: "Orta Saha",
    foot: "right",
    photo: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    name: "Caner",
    age: 31,
    rating: 4.5,
    position: "Defans",
    foot: "right",
    photo: "https://via.placeholder.com/150",
  },
  {
    id: 4,
    name: "Isa Can",
    age: 26,
    rating: 9,
    position: "Kaleci",
    foot: "left",
    photo: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    name: "Hayri Sencer",
    age: 29,
    rating: 8.5,
    position: "Orta Saha",
    foot: "right",
    photo: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    name: "Muhammet Furkan",
    age: 23,
    rating: 6.2,
    position: "Forvet",
    foot: "left",
    photo: "https://via.placeholder.com/150",
  },
];
